# Ghidra Jython script: Extract struct definitions from data type manager
# Outputs C header content and JSON summary
# @category Analysis

import json

from ghidra.program.model.data import Structure, Enum


def get_structs():
    """Extract struct definitions from Ghidra's data type manager."""
    dtm = currentProgram.getDataTypeManager()
    structs = []

    for dt in dtm.getAllStructures():
        if isinstance(dt, Structure):
            fields = []
            for i in range(dt.getNumComponents()):
                comp = dt.getComponent(i)
                if comp is not None:
                    fields.append({
                        "name": comp.getFieldName() or ("field_0x%x" % comp.getOffset()),
                        "type": str(comp.getDataType()),
                        "offset": comp.getOffset(),
                        "size": comp.getLength(),
                    })
            structs.append({
                "name": dt.getName(),
                "size": dt.getLength(),
                "num_fields": dt.getNumComponents(),
                "fields": fields,
                "category": str(dt.getCategoryPath()),
            })
    return structs


def get_enums():
    """Extract enum definitions."""
    dtm = currentProgram.getDataTypeManager()
    enums = []

    for dt in dtm.getAllDataTypes():
        if isinstance(dt, Enum):
            values = {}
            for name in dt.getNames():
                values[name] = dt.getValue(name)
            enums.append({
                "name": dt.getName(),
                "size": dt.getLength(),
                "values": values,
            })
    return enums


def generate_c_header(structs):
    """Generate C header content from struct definitions."""
    lines = [
        "/* Reconstructed struct definitions from Ghidra analysis */",
        "/* Generated by reconstruct_structs.py */",
        "",
        "#ifndef _RECONSTRUCTED_STRUCTS_H",
        "#define _RECONSTRUCTED_STRUCTS_H",
        "",
        "#include <stdint.h>",
        "",
    ]

    type_map = {
        "byte": "uint8_t",
        "word": "uint16_t",
        "dword": "uint32_t",
        "qword": "uint64_t",
        "char": "char",
        "int": "int32_t",
        "uint": "uint32_t",
        "short": "int16_t",
        "ushort": "uint16_t",
        "long": "int32_t",
        "ulong": "uint32_t",
        "pointer": "void *",
    }

    for struct in structs:
        lines.append("typedef struct {")
        for field in struct["fields"]:
            c_type = type_map.get(field["type"].lower(), field["type"])
            lines.append("    %s %s;  /* offset: 0x%x, size: %d */" % (
                c_type, field["name"], field["offset"], field["size"]))
        lines.append("} %s;  /* total size: %d */" % (struct["name"], struct["size"]))
        lines.append("")

    lines.append("#endif /* _RECONSTRUCTED_STRUCTS_H */")
    return "\n".join(lines)


def main():
    structs = get_structs()
    enums = get_enums()
    header_content = generate_c_header(structs)

    result = {
        "binary": currentProgram.getName(),
        "type": "structs",
        "struct_count": len(structs),
        "enum_count": len(enums),
        "structs": structs,
        "enums": enums,
        "header_content": header_content,
    }
    print("===GHIDRA_JSON_BEGIN===")
    print(json.dumps(result, indent=2))
    print("===GHIDRA_JSON_END===")


main()
